In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [3]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.0 kB 682.7 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 651.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   - -------------------------------------- 0.4/15.5 MB 12.2 MB/s eta 0:00:02
   -- ------------------------------------- 1.1/15.5 MB 13.5 MB/s eta 0:00:02
   ---- ----------------------------------- 1.7/15.5 MB 13.4 MB/s eta 0:00:02
   ----- ---------------------------------- 2.3/15.5 MB 13.2 MB/s eta 0:00:02
   ------ --------------------------------- 2.4/15.5 MB 10.8 MB/s eta 0:00:02
   ------- -------------------------------- 3.0/15.5 MB 11.4 MB/s eta 0:00:02
   -------- ------------------------------- 3.4/15.5 MB 10.8 MB/s eta 0:00:02
   --------- ------------------------------ 3.6/15.5 MB 10.3 MB/s eta 0:00:02
   ---------- ----------------------------- 3.9/15.5 MB 9.7 MB/s eta 0:00:

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [4]:
import numpy as np

In [9]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [10]:
a = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.4/11.5 MB 12.9 MB/s eta 0:00:01
   ----- ---------------------------------- 1.5/11.5 MB 19.0 MB/s eta 0:00:01
   ------- -------------------------------- 2.1/11.5 MB 19.0 MB/s eta 0:00:01
   ------- -------------------------------- 2.1/11.5 MB 19.0 MB/s eta 0:00:01
   ------- -------------------------------- 2.1/11.5 MB 19.0 MB/s eta 0:00:01
   ------- -------------------------------- 2.1/11.5 MB 19.0 MB/s eta 0:00:01
   ------- -------------------------------- 2.1/11.5 MB 19.0 MB/s eta 0:00:01
   ------- -------------------------------- 2.1/11.5 MB 19.0 MB/s eta 0:00:01
   -------- ------------------------------- 2.4/11.5 MB 5.8 MB/s eta 0:00:02
   ----------- ---------------------------- 3.3/11.5 MB 7.3 MB/s eta 0:00:02
   ------------- -------------------------- 4.0/11.5 MB 8.0 MB/s eta 0:00:01
   -------------- ------------------------- 4.3/11.5 MB 8.3 MB/s eta 0:00:0

In [12]:
print (a.shape)

(2, 5)


In [14]:
b = a.reshape(2,5)

In [15]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
x=np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [18]:
print(type(x))

<class 'numpy.ndarray'>


In [20]:
x=np.ones([2,3],dtype ="int")
x

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
a=np.array([[1,2,3],[4,5,6]])
reshape_a = a.reshape(3,2)


In [24]:
transpose_a = a.transpose()
print(transpose_a)

[[1 4]
 [2 5]
 [3 6]]


In [29]:
a = np.arange(0,24,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [30]:
a=np.arange(10,20,2)
a

array([10, 12, 14, 16, 18])

In [32]:
x=np.linspace(10,20,5)
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [7]:
nums = [7,5,7,2]
target = 9
def sumtwo( nums,target):
    for i in range(len(nums)):
        for j in range(len(nums)):
            if i!= j:
                if(nums[i]+nums[j] == target):
                    return list([i,j])

In [8]:
print(sumtwo(nums,target))


[0, 3]


In [1]:
a=121%10
x= int(121/10)
print(x)
print(len(x))

12


TypeError: object of type 'int' has no len()